### ISSUE TITLE
Check on the warnings

### ISSUE THREAD

**Issue by drstarson** [Passiolife/Passio-iOS-QuickStart#1]
@Pratik7u pls check on the warnings below. The app works and builds well, but I am getting the warnings when running the app. This happens in the gallery mode.

![Screenshot 2024-11-26 at 8 58 53 PM](https://github.com/user-attachments/assets/dc1b103c-f65a-48d3-9681-7eaf49145938)

**Comment by drstarson** [comment]
@Pratik7u any updates on this? If fixing this requires a lot of work, we can ICEBOX for now. Just let me know.

**Comment by Pratik7u** [comment]
@drstarson I will have to debug and see why it is giving warnings. Currently on Dr. berg tasks..

**Comment by drstarson** [comment]
O.k., let's keep this as an IceBox. Not urgent. The issue is most likely coming from an outdated volume estimation feature which we are not using any more. We will remove it later.
